_mergedCuts = []
for cut in list(cuts.keys()):
    __cutExpr = ''
    if type(cuts[cut]) == dict:
        __cutExpr = cuts[cut]['expr']
        for cat in list(cuts[cut]['categories'].keys()):
            _mergedCuts.append(cut + '_' + cat)
    elif type(cuts[cut]) == str:
        _mergedCuts.append(cut)

cuts2j = _mergedCuts

variables = {}


variables['tree'] = {
    'tree' : {
        'event' : 'event',
####### detajj
        'detajj' : 'detajj',
        'detajj_absolute_up' : 'detajj_jesRegroed_Absoluteup',
        'detajj_absolute_down' : 'detajj_jesRegroed_Absolutedo',
        'detajj_relativebal_up' : 'detajj_jesRegroed_RelativeBalup',
        'detajj_relativebal_down' : 'detajj_jesRegroed_RelativeBaldo',
        'detajj_jer_up' : 'detajj_jerup',
        'detajj_jer_down' : 'detajj_jerdo',
        'detajj_bbec1_up' : 'detajj_jesRegroed_BBEC1_2024up',
        'detajj_bbec1_down' : 'detajj_jesRegroed_BBEC1_2024do',
        'detajj_hf_up' : 'detajj_jesRegroed_HF_2024up',
        'detajj_hf_down' : 'detajj_jesRegroed_HF_2024do',
        'detajj_absolute2024_up' : 'detajj_jesRegroed_Absolute_2024up',
        'detajj_absolute2024_down' : 'detajj_jesRegroed_Absolute_2024do',
####### dphill
        'dphill' : 'dphill',
        'dphill_absolute_up' : 'dphill_jesRegroed_Absoluteup',
        'dphill_absolute_down' : 'dphill_jesRegroed_Absolutedo',
        'dphill_relativebal_up' : 'dphill_jesRegroed_RelativeBalup',
        'dphill_relativebal_down' : 'dphill_jesRegroed_RelativeBaldo',
        'dphill_jer_up' : 'dphill_jerup',
        'dphill_jer_down' : 'dphill_jerdo',
        'dphill_bbec1_up' : 'dphill_jesRegroed_BBEC1_2024up',
        'dphill_bbec1_down' : 'dphill_jesRegroed_BBEC1_2024do',
        'dphill_hf_up' : 'dphill_jesRegroed_HF_2024up',
        'dphill_hf_down' : 'dphill_jesRegroed_HF_2024do',
        'dphill_absolute2024_up' : 'dphill_jesRegroed_Absolute_2024up',
        'dphill_absolute2024_down' : 'dphill_jesRegroed_Absolute_2024do',
####### drll
        'drll' : 'drll',
        'drll_absolute_up' : 'drll_jesRegroed_Absoluteup',
        'drll_absolute_down' : 'drll_jesRegroed_Absolutedo',
        'drll_relativebal_up' : 'drll_jesRegroed_RelativeBalup',
        'drll_relativebal_down' : 'drll_jesRegroed_RelativeBaldo',
        'drll_jer_up' : 'drll_jerup',
        'drll_jer_down' : 'drll_jerdo',
        'drll_bbec1_up' : 'drll_jesRegroed_BBEC1_2024up',
        'drll_bbec1_down' : 'drll_jesRegroed_BBEC1_2024do',
        'drll_hf_up' : 'drll_jesRegroed_HF_2024up',
        'drll_hf_down' : 'drll_jesRegroed_HF_2024do',
        'drll_absolute2024_up' : 'drll_jesRegroed_Absolute_2024up',
        'drll_absolute2024_down' : 'drll_jesRegroed_Absolute_2024do',
####### mjj
        'mjj' : 'mjj',
        'mjj_absolute_up' : 'mjj_jesRegroed_Absoluteup',
        'mjj_absolute_down' : 'mjj_jesRegroed_Absolutedo',
        'mjj_relativebal_up' : 'mjj_jesRegroed_RelativeBalup',
        'mjj_relativebal_down' : 'mjj_jesRegroed_RelativeBaldo',
        'mjj_jer_up' : 'mjj_jerup',
        'mjj_jer_down' : 'mjj_jerdo',
        'mjj_bbec1_up' : 'mjj_jesRegroed_BBEC1_2024up',
        'mjj_bbec1_down' : 'mjj_jesRegroed_BBEC1_2024do',
        'mjj_hf_up' : 'mjj_jesRegroed_HF_2024up',
        'mjj_hf_down' : 'mjj_jesRegroed_HF_2024do',
        'mjj_absolute2024_up' : 'mjj_jesRegroed_Absolute_2024up',
        'mjj_absolute2024_down' : 'mjj_jesRegroed_Absolute_2024do',
####### ht
        'ht' : 'ht',
        'ht_absolute_up' : 'ht_jesRegroed_Absoluteup',
        'ht_absolute_down' : 'ht_jesRegroed_Absolutedo',
        'ht_relativebal_up' : 'ht_jesRegroed_RelativeBalup',
        'ht_relativebal_down' : 'ht_jesRegroed_RelativeBaldo',
        'ht_jer_up' : 'ht_jerup',
        'ht_jer_down' : 'ht_jerdo',
        'ht_bbec1_up' : 'ht_jesRegroed_BBEC1_2024up',
        'ht_bbec1_down' : 'ht_jesRegroed_BBEC1_2024do',
        'ht_hf_up' : 'ht_jesRegroed_HF_2024up',
        'ht_hf_down' : 'ht_jesRegroed_HF_2024do',
        'ht_absolute2024_up' : 'ht_jesRegroed_Absolute_2024up',
        'ht_absolute2024_down' : 'ht_jesRegroed_Absolute_2024do',
####### mth
        'mth' : 'mth',
        'mth_absolute_up' : 'mth_jesRegroed_Absoluteup',
        'mth_absolute_down' : 'mth_jesRegroed_Absolutedo',
        'mth_relativebal_up' : 'mth_jesRegroed_RelativeBalup',
        'mth_relativebal_down' : 'mth_jesRegroed_RelativeBaldo',
        'mth_jer_up' : 'mth_jerup',
        'mth_jer_down' : 'mth_jerdo',
        'mth_bbec1_up' : 'mth_jesRegroed_BBEC1_2024up',
        'mth_bbec1_down' : 'mth_jesRegroed_BBEC1_2024do',
        'mth_hf_up' : 'mth_jesRegroed_HF_2024up',
        'mth_hf_down' : 'mth_jesRegroed_HF_2024do',
        'mth_absolute2024_up' : 'mth_jesRegroed_Absolute_2024up',
        'mth_absolute2024_down' : 'mth_jesRegroed_Absolute_2024do',
####### mll
        'mll' : 'mll',
        'mll_absolute_up' : 'mll_jesRegroed_Absoluteup',
        'mll_absolute_down' : 'mll_jesRegroed_Absolutedo',
        'mll_relativebal_up' : 'mll_jesRegroed_RelativeBalup',
        'mll_relativebal_down' : 'mll_jesRegroed_RelativeBaldo',
        'mll_jer_up' : 'mll_jerup',
        'mll_jer_down' : 'mll_jerdo',
        'mll_bbec1_up' : 'mll_jesRegroed_BBEC1_2024up',
        'mll_bbec1_down' : 'mll_jesRegroed_BBEC1_2024do',
        'mll_hf_up' : 'mll_jesRegroed_HF_2024up',
        'mll_hf_down' : 'mll_jesRegroed_HF_2024do',
        'mll_absolute2024_up' : 'mll_jesRegroed_Absolute_2024up',
        'mll_absolute2024_down' : 'mll_jesRegroed_Absolute_2024do',
####### puppimet
        'puppimet' : 'PuppiMET_pt',
        'puppimet_absolute_up' : 'PuppiMET_pt_jesRegroed_Absoluteup',
        'puppimet_absolute_down' : 'PuppiMET_pt_jesRegroed_Absolutedo',
        'puppimet_relativebal_up' : 'PuppiMET_pt_jesRegroed_RelativeBalup',
        'puppimet_relativebal_down' : 'PuppiMET_pt_jesRegroed_RelativeBaldo',
        'puppimet_jer_up' : 'PuppiMET_pt_jerup',
        'puppimet_jer_down' : 'PuppiMET_pt_jerdo',
        'puppimet_bbec1_up' : 'PuppiMET_pt_jesRegroed_BBEC1_2024up',
        'puppimet_bbec1_down' : 'PuppiMET_pt_jesRegroed_BBEC1_2024do',
        'puppimet_hf_up' : 'PuppiMET_pt_jesRegroed_HF_2024up',
        'puppimet_hf_down' : 'PuppiMET_pt_jesRegroed_HF_2024do',
        'puppimet_absolute2024_up' : 'PuppiMET_pt_jesRegroed_Absolute_2024up',
        'puppimet_absolute2024_down' : 'PuppiMET_pt_jesRegroed_Absolute_2024do',
####### eta1
        'eta1' : 'Lepton_eta[0]',
####### eta2
        'eta2' : 'Lepton_eta[1]',
####### pt1
        'pt1' : 'Lepton_pt[0]',   
####### pt2
        'pt2' : 'Lepton_pt[1]',   
####### jeteta1
        'jeteta1' : 'Alt(CleanJet_eta, 0, -99)',
        'jeteta1_absolute_up' : 'Alt(CleanJet_eta_jesRegroed_Absoluteup, 0, -99)',
        'jeteta1_absolute_down' : 'Alt(CleanJet_eta_jesRegroed_Absolutedo, 0, -99)',
        'jeteta1_relativebal_up' : 'Alt(CleanJet_eta_jesRegroed_RelativeBalup, 0, -99)',
        'jeteta1_relativebal_down' : 'Alt(CleanJet_eta_jesRegroed_RelativeBaldo, 0, -99)',
        'jeteta1_jer_up' : 'Alt(CleanJet_eta_jerup, 0, -99)',
        'jeteta1_jer_down' : 'Alt(CleanJet_eta_jerdo, 0, -99)',
        'jeteta1_bbec1_up' : 'Alt(CleanJet_eta_jesRegroed_BBEC1_2024up, 0, -99)',
        'jeteta1_bbec1_down' : 'Alt(CleanJet_eta_jesRegroed_BBEC1_2024do, 0, -99)',
        'jeteta1_hf_up' : 'Alt(CleanJet_eta_jesRegroed_HF_2024up, 0, -99)',
        'jeteta1_hf_down' : 'Alt(CleanJet_eta_jesRegroed_HF_2024do, 0, -99)',
        'jeteta1_absolute2024_up' : 'Alt(CleanJet_eta_jesRegroed_Absolute_2024up, 0, -99)',
        'jeteta1_absolute2024_down' : 'Alt(CleanJet_eta_jesRegroed_Absolute_2024do, 0, -99)',
####### jeteta2
        'jeteta2' : 'Alt(CleanJet_eta, 1, -99)',
        'jeteta2_absolute_up' : 'Alt(CleanJet_eta_jesRegroed_Absoluteup, 1, -99)',
        'jeteta2_absolute_down' : 'Alt(CleanJet_eta_jesRegroed_Absolutedo, 1, -99)',
        'jeteta2_relativebal_up' : 'Alt(CleanJet_eta_jesRegroed_RelativeBalup, 1, -99)',
        'jeteta2_relativebal_down' : 'Alt(CleanJet_eta_jesRegroed_RelativeBaldo, 1, -99)',
        'jeteta2_jer_up' : 'Alt(CleanJet_eta_jerup, 1, -99)',
        'jeteta2_jer_down' : 'Alt(CleanJet_eta_jerdo, 1, -99)',
        'jeteta2_bbec1_up' : 'Alt(CleanJet_eta_jesRegroed_BBEC1_2024up, 1, -99)',
        'jeteta2_bbec1_down' : 'Alt(CleanJet_eta_jesRegroed_BBEC1_2024do, 1, -99)',
        'jeteta2_hf_up' : 'Alt(CleanJet_eta_jesRegroed_HF_2024up, 1, -99)',
        'jeteta2_hf_down' : 'Alt(CleanJet_eta_jesRegroed_HF_2024do, 1, -99)',
        'jeteta2_absolute2024_up' : 'Alt(CleanJet_eta_jesRegroed_Absolute_2024up, 1, -99)',
        'jeteta2_absolute2024_down' : 'Alt(CleanJet_eta_jesRegroed_Absolute_2024do, 1, -99)',
####### jetpt1
        'jetpt1' : 'Alt(CleanJet_pt, 0, -99)',
        'jetpt1_absolute_up' : 'Alt(CleanJet_pt_jesRegroed_Absoluteup, 0, -99)',
        'jetpt1_absolute_down' : 'Alt(CleanJet_pt_jesRegroed_Absolutedo, 0, -99)',
        'jetpt1_relativebal_up' : 'Alt(CleanJet_pt_jesRegroed_RelativeBalup, 0, -99)',
        'jetpt1_relativebal_down' : 'Alt(CleanJet_pt_jesRegroed_RelativeBaldo, 0, -99)',
        'jetpt1_jer_up' : 'Alt(CleanJet_pt_jerup, 0, -99)',
        'jetpt1_jer_down' : 'Alt(CleanJet_pt_jerdo, 0, -99)',
        'jetpt1_bbec1_up' : 'Alt(CleanJet_pt_jesRegroed_BBEC1_2024up, 0, -99)',
        'jetpt1_bbec1_down' : 'Alt(CleanJet_pt_jesRegroed_BBEC1_2024do, 0, -99)',
        'jetpt1_hf_up' : 'Alt(CleanJet_pt_jesRegroed_HF_2024up, 0, -99)',
        'jetpt1_hf_down' : 'Alt(CleanJet_pt_jesRegroed_HF_2024do, 0, -99)',
        'jetpt1_absolute2024_up' : 'Alt(CleanJet_pt_jesRegroed_Absolute_2024up, 0, -99)',
        'jetpt1_absolute2024_down' : 'Alt(CleanJet_pt_jesRegroed_Absolute_2024do, 0, -99)',
####### jetpt2
        'jetpt2' : 'Alt(CleanJet_pt, 1, -99)',
        'jetpt2_absolute_up' : 'Alt(CleanJet_pt_jesRegroed_Absoluteup, 1, -99)',
        'jetpt2_absolute_down' : 'Alt(CleanJet_pt_jesRegroed_Absolutedo, 1, -99)',
        'jetpt2_relativebal_up' : 'Alt(CleanJet_pt_jesRegroed_RelativeBalup, 1, -99)',
        'jetpt2_relativebal_down' : 'Alt(CleanJet_pt_jesRegroed_RelativeBaldo, 1, -99)',
        'jetpt2_jer_up' : 'Alt(CleanJet_pt_jerup, 1, -99)',
        'jetpt2_jer_down' : 'Alt(CleanJet_pt_jerdo, 1, -99)',
        'jetpt2_bbec1_up' : 'Alt(CleanJet_pt_jesRegroed_BBEC1_2024up, 1, -99)',
        'jetpt2_bbec1_down' : 'Alt(CleanJet_pt_jesRegroed_BBEC1_2024do, 1, -99)',
        'jetpt2_hf_up' : 'Alt(CleanJet_pt_jesRegroed_HF_2024up, 1, -99)',
        'jetpt2_hf_down' : 'Alt(CleanJet_pt_jesRegroed_HF_2024do, 1, -99)',
        'jetpt2_absolute2024_up' : 'Alt(CleanJet_pt_jesRegroed_Absolute_2024up, 1, -99)',
        'jetpt2_absolute2024_down' : 'Alt(CleanJet_pt_jesRegroed_Absolute_2024do, 1, -99)',
####### dphillmet
        'dphillmet' : 'dphillmet',
        'dphillmet_absolute_up' : 'dphillmet_jesRegroed_Absoluteup',
        'dphillmet_absolute_down' : 'dphillmet_jesRegroed_Absolutedo',
        'dphillmet_relativebal_up' : 'dphillmet_jesRegroed_RelativeBalup',
        'dphillmet_relativebal_down' : 'dphillmet_jesRegroed_RelativeBaldo',
        'dphillmet_jer_up' : 'dphillmet_jerup',
        'dphillmet_jer_down' : 'dphillmet_jerdo',
        'dphillmet_bbec1_up' : 'dphillmet_jesRegroed_BBEC1_2024up',
        'dphillmet_bbec1_down' : 'dphillmet_jesRegroed_BBEC1_2024do',
        'dphillmet_hf_up' : 'dphillmet_jesRegroed_HF_2024up',
        'dphillmet_hf_down' : 'dphillmet_jesRegroed_HF_2024do',
        'dphillmet_absolute2024_up' : 'dphillmet_jesRegroed_Absolute_2024up',
        'dphillmet_absolute2024_down' : 'dphillmet_jesRegroed_Absolute_2024do',
####### ptll
        'ptll' : 'ptll',
        'ptll_absolute_up' : 'ptll_jesRegroed_Absoluteup',
        'ptll_absolute_down' : 'ptll_jesRegroed_Absolutedo',
        'ptll_relativebal_up' : 'ptll_jesRegroed_RelativeBalup',
        'ptll_relativebal_down' : 'ptll_jesRegroed_RelativeBaldo',
        'ptll_jer_up' : 'ptll_jerup',
        'ptll_jer_down' : 'ptll_jerdo',
        'ptll_bbec1_up' : 'ptll_jesRegroed_BBEC1_2024up',
        'ptll_bbec1_down' : 'ptll_jesRegroed_BBEC1_2024do',
        'ptll_hf_up' : 'ptll_jesRegroed_HF_2024up',
        'ptll_hf_down' : 'ptll_jesRegroed_HF_2024do',
        'ptll_absolute2024_up' : 'ptll_jesRegroed_Absolute_2024up',
        'ptll_absolute2024_down' : 'ptll_jesRegroed_Absolute_2024do',
####### Ctot
        'Ctot' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta[0]-CleanJet_eta[1])+abs(2*Lepton_eta[1]-CleanJet_eta[0]-CleanJet_eta[1]))/detajj)',
        'Ctot_absolute_up' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_Absoluteup[0]-CleanJet_eta_jesRegroed_Absoluteup[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_Absoluteup[0]-CleanJet_eta_jesRegroed_Absoluteup[1]))/detajj_jesRegroed_Absoluteup)',
        'Ctot_absolute_down' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_Absolutedo[0]-CleanJet_eta_jesRegroed_Absolutedo[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_Absolutedo[0]-CleanJet_eta_jesRegroed_Absolutedo[1]))/detajj_jesRegroed_Absolutedo)',
        'Ctot_relativebal_up' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_RelativeBalup[0]-CleanJet_eta_jesRegroed_RelativeBalup[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_RelativeBalup[0]-CleanJet_eta_jesRegroed_RelativeBalup[1]))/detajj_jesRegroed_RelativeBalup)',
        'Ctot_relativebal_down' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_RelativeBaldo[0]-CleanJet_eta_jesRegroed_RelativeBaldo[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_RelativeBaldo[0]-CleanJet_eta_jesRegroed_RelativeBaldo[1]))/detajj_jesRegroed_RelativeBaldo)',
        'Ctot_jer_up' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jerup[0]-CleanJet_eta_jerup[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jerup[0]-CleanJet_eta_jerup[1]))/detajj_jerup)',
        'Ctot_jer_down' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jerdo[0]-CleanJet_eta_jerdo[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jerdo[0]-CleanJet_eta_jerdo[1]))/detajj_jerdo)',
        'Ctot_bbec1_up' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_BBEC1_2024up[0]-CleanJet_eta_jesRegroed_BBEC1_2024up[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_BBEC1_2024up[0]-CleanJet_eta_jesRegroed_BBEC1_2024up[1]))/detajj_jesRegroed_BBEC1_2024up)',
        'Ctot_bbec1_down' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_BBEC1_2024do[0]-CleanJet_eta_jesRegroed_BBEC1_2024do[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_BBEC1_2024do[0]-CleanJet_eta_jesRegroed_BBEC1_2024do[1]))/detajj_jesRegroed_BBEC1_2024do)',
        'Ctot_hf_up' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_HF_2024up[0]-CleanJet_eta_jesRegroed_HF_2024up[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_HF_2024up[0]-CleanJet_eta_jesRegroed_HF_2024up[1]))/detajj_jesRegroed_HF_2024up)',
        'Ctot_hf_down' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_HF_2024do[0]-CleanJet_eta_jesRegroed_HF_2024do[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_HF_2024do[0]-CleanJet_eta_jesRegroed_HF_2024do[1]))/detajj_jesRegroed_HF_2024do)',
        'Ctot_absolute2024_up' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_Absolute_2024up[0]-CleanJet_eta_jesRegroed_Absolute_2024up[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_Absolute_2024up[0]-CleanJet_eta_jesRegroed_Absolute_2024up[1]))/detajj_jesRegroed_Absolute_2024up)',
        'Ctot_absolute2024_down' : 'log((abs(2*Lepton_eta[0]-CleanJet_eta_jesRegroed_Absolute_2024do[0]-CleanJet_eta_jesRegroed_Absolute_2024do[1])+abs(2*Lepton_eta[1]-CleanJet_eta_jesRegroed_Absolute_2024do[0]-CleanJet_eta_jesRegroed_Absolute_2024do[1]))/detajj_jesRegroed_Absolute_2024do)',
######## mlj11
        'mlj11' : 'm_lj[0]',
######## mlj12
        'mlj12' : 'm_lj[1]',
######## mlj21
        'mlj21' : 'm_lj[2]',
######## mlj22
        'mlj22' : 'm_lj[3]',
####### mtw2
        'mtw2' : 'mtw2',
        'mtw2_absolute_up' : 'mtw2_jesRegroed_Absoluteup',
        'mtw2_absolute_down' : 'mtw2_jesRegroed_Absolutedo',
        'mtw2_relativebal_up' : 'mtw2_jesRegroed_RelativeBalup',
        'mtw2_relativebal_down' : 'mtw2_jesRegroed_RelativeBaldo',
        'mtw2_jer_up' : 'mtw2_jerup',
        'mtw2_jer_down' : 'mtw2_jerdo',
        'mtw2_bbec1_up' : 'mtw2_jesRegroed_BBEC1_2024up',
        'mtw2_bbec1_down' : 'mtw2_jesRegroed_BBEC1_2024do',
        'mtw2_hf_up' : 'mtw2_jesRegroed_HF_2024up',
        'mtw2_hf_down' : 'mtw2_jesRegroed_HF_2024do',
        'mtw2_absolute2024_up' : 'mtw2_jesRegroed_Absolute_2024up',
        'mtw2_absolute2024_down' : 'mtw2_jesRegroed_Absolute_2024do',
######### weights
        'PS_ISR_d' : 'PSWeight[2]',
        'PS_ISR_u' : 'PSWeight[0]',
        'PS_FSR_d' : 'PSWeight[3]',
        'PS_FSR_u' : 'PSWeight[1]',
        'btagSF_bc_corr_up' : 'btagSFbc_up_correlated/btagSFbc',
        'btagSF_bc_corr_down' : 'btagSFbc_down_correlated/btagSFbc',
    },
    'cuts' : ['hww_sr'],
    'blind' : dict([(cut, 'full') for cut in cuts2j if 'hww_sr' in cut])
}